### PR TITLE
Student A

### LINKED ISSUE #3: [3pt]  - Add tests for items counter - Student A
Make sure that function for the items counter is covered with unit tests using Jest. Make sure that you have tests for all edge cases.

### LINKED ISSUE #6: [3pt]  - Add all items counter on the Homepage - Student A
Even if the API gives you the number of items, you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Homepage.

Respect the following rules:

- Each counter should be implemented as a separate module.
- A counter function should look for specific DOM elements (e.g. for the comments counter it should look for comments) and make the counting based on what is actually displayed on the page.
- A counter function should cover all the edge cases you can think about.

### LINKED ISSUE #9: [3pt]  - Create feature: add  new like - Student A
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

### LINKED ISSUE #12: [4pt]  - Display number of likes for each item on the Homepage - Student A
When the page loads, the webapp the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item likes and combines them with the data from the base API.

Remember that your page should make only 2 requests:
- one to the base API
- and **one** to the Involvement API.

This task **does not** include displaying the likes button (heart icon on the wireframe) for each item.

### LINKED ISSUE #15: [4pt]  - Display list of items on the Homepage - Student A
Create the main part of the homepage that keeps the layout from the wireframe: 

Screenshot 2021-06-27 at 21 50 23

When the page loads, the webapp retrieves data from  the selected API and shows the list of items on screen with the basic data (e.g. title + image).

Prepare also "Comments" and "Reservations" buttons. They should be doing nothing - just being displayed.

This task **does not** include displaying the number of likes for each item.

This task **does not** include the counter of the items.

### LINKED ISSUE #17: [0.5pt] Add header - group task
Create page header according to the wireframe:

Screenshot 2021-06-27 at 21 42 24

### LINKED ISSUE #19: [1pt] Choose assets - group task
Choose images, text, icons, fonts.

### LINKED ISSUE #20: [0.5pt] Find external API - group task
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

### PR DESCRIPTION
**Pull request by soesandarwin2201**
## What does this PR do?
This PR is raised to  create the home page for the food app with the data of MealDB api.

## Description of the task to be completed
- [x] create a new branch (studentA)
- [x] create the section to contain the items in index.html file
- [x] create getData function to get the data from api
- [x] create PostData function to post the data when the page is loaded
- [x] create displayMeal function to display the item on home page
- [x] make styling for meal items
- [x] create LikeGetData function from the involvement api for likes
- [x] create the likePostData funtion to post the data for like       
## How should it be tested
Clone the repository
```
git clone  https://github.com/KIsmoilov/JS-Capstone-Project
```
Navigate to the folder
```
cd JS-Capstone-Project
```
Checkout the branch
```
git checkout StudentA
```
#### Thanks for reviewing my PR :blush:

### CODE REVIEW

**Review by KIsmoilov — APPROVED** [review]
## STATUS: Approved  💯

## Hi @soesandarwin2201  👋, 

Good job! You did a good job!  Enjoy for the rest of your coding
## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Asynchronous functions have been used ✔️
- Nice design ✔️




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Comment by soesandarwin2201** [comment]
## What does this PR do?
This PR is raised to  give update to my coding partners about my project.

## Description of the task to be completed
- [x] create the setLike functiom to get the id of meal and id of like data
- [x] create a event listener for heart icon and call the postdata and dispaly likes
- [x] fix the bug of heart button refresh problem
- [x] create the test file for homeItemCounter 
- [x] check the linters   
## How should it be tested
Clone the repository
```
git clone https://github.com/KIsmoilov/JS-Capstone-Project
```
Navigate to the folder
```
cd JS-capstone-Project
```
Checkout the branch
```
git checkout StudentA
```
#### Thanks for reviewing my PR :blush:

**Review by KIsmoilov — CHANGES_REQUESTED** [review]
Hi @soesandarwin2201  , 

You did a great job so far!👏 
You've done almost all of the requested changes, but there is a need for some improvements.

almost4

 ## Highlights 💯 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Asynchronous functions have been used ✔️
- Beautiful design ✔️

 ## Required Changes ♻️
 - Please add some styling for your like button using CSS on hover and active events.
 - On your nav bar it would be great if you change the home to meals so that the meals counter will look related to each other.
 
https://github.com/KIsmoilov/JS-Capstone-Project/blob/704efc40e72d50d0d659a1b1fc37dafc1f777638/src/index.html#L26-L27

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Review by KIsmoilov — APPROVED** [review]
## STATUS: Approved  💯

## Hi @soesandarwin2201  👋, 

Good job! You did a good job! 
## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Asynchronous functions have been used ✔️
- Nice design ✔️




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Pull request merged**
